Bugfix/atc 191
n8rzz/atc pull request #201
Opened 2016-12-14 15:59 UTC by Dabea

This will fixes the bug where parseElevation() returns Nan

2016-12-14 21:31 UTC, n8rzz requested changes

2016-12-14 21:31 UTC, n8rzz commented on CHANGELOG.md
> +- Fixes `parseElevation()` so that it dose not return NaN when it is given the string `'Infinity'` [#191] (https://github.com/n8rzz/atc/issues/191)
I think you meant to use `does` here and not `dose`

2016-12-14 21:31 UTC, n8rzz commented on CHANGELOG.md
> +- Fixes `parseElevation()` so that it dose not return NaN when it is given the string `'Infinity'` [#191] (https://github.com/n8rzz/atc/issues/191)
could you also add a link to the origin zlsa issue here too?  see this PR for an example of how that should be formatted: https://github.com/n8rzz/atc/pull/198/files

2016-12-14 21:31 UTC, n8rzz commented on src/assets/scripts/utilities/unitConverters.js
> +    if (elevation === 'Infinity' || elevation === '-Infinity')  {
This is the correct logic, I can see the tests are passing, but I would prefer to combine the logic here with the logic on line 269:
```javascript
if (_isNumber(elevation) || elevation === 'Infinity' || elevation === '-Infinity') {
    return parseFloat(elevation);
}
```

could you also add a comment about why we are looking for strings here?

2016-12-18 02:20 UTC, Dabea commented
I added comments and merged the if statements
Also fixed the spelling error and added a link to the original issue.

2016-12-18 02:50 UTC, n8rzz submitted a review, later dismissed

2016-12-18 02:55 UTC, n8rzz commented on src/assets/scripts/utilities/unitConverters.js
> +    if (_isNumber(elevation || elevation === 'Infinity' || elevation === '-Infinity')) {
here it is.  sorry I missed this.  this should actually be:
```javascript
if (_isNumber(elevation) || elevation === 'Infinity' || elevation === '-Infinity') { }
```

2016-12-18 04:03 UTC, n8rzz approved these changes
:shipit:

2016-12-18 04:42 UTC, merged