formated white space on variables and in display text
n8rzz/atc pull request #222
Opened 2016-12-18 08:08 UTC by Dabea

I have found a few things in `AircraftInstanceModel` that should help with spacing. I searched though many other files but did not see anything else. If you have any other files that might be a good candidate to be searched though let me know.

2016-12-18 15:52 UTC, n8rzz commented
I'd like for mr @erikquinn to look at this one.  there are _a lot_ of strings that get sent to the UI and, although I know where most of them are, I'd like for him to be the final word on this PR. 😉

2016-12-18 22:21 UTC, erikquinn requested changes
The only other problems I'm seeing space-wise are:

 - trailing space at `AircraftInstanceModel.js:939` needs to be removed
 - `AircraftInstanceModel.runAltitude()` should be amended such that its returns do not end with a space when `expedite` is an empty string

Udda den DAT, every ting A-OK!
^ ([in case you don't get the reference](https://www.youtube.com/watch?v=_IqWal_EmBg) :wink:)

2016-12-18 22:21 UTC, erikquinn commented on src/assets/scripts/aircraft/AircraftInstanceModel.js
> +            heavy = 'super';
Further down in this function, this variable gets used in ``` cs += ` ${radio_spellOut(callsign)} ${heavy}`; ```. If the aircraft is neither "heavy" nor "super", then `heavy` will remain an empty string, which would yield a second space in the returned callsign.

Now that I think about it, it's only using this to speak the callsign aloud, so it actually shouldn't really matter.

2016-12-19 15:17 UTC, n8rzz commented
@Dabea updated with #220 file structure. be sure to re-pull before continuing work on this one.

2016-12-20 09:15 UTC, Dabea commented
Looks Like i did not push my last changes before the update. This will address the extra space until the expedite method is added.

Also should I add these changes under minor changes for 3.3.0 as well?

2016-12-20 15:44 UTC, n8rzz commented
@Dabea yes please. v3.3.0 only please.

2016-12-27 09:49 UTC, Dabea commented
This one is complete and  can be merged (unless i am missing something)

2016-12-30 03:09 UTC, erikquinn approved these changes

2016-12-30 15:25 UTC, merged